---
- name: del apaches
  hosts: all
  become: yes

  tasks:

  - name: dell apache
    yum: name=httpd state=removed
    
    when: ansible_os_family=='RedHat'

    

  - name: dell debian
    apt: name=apache2 state=absent
    
    when: ansible_os_family=='Debian'

    
